<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Blog\Component\Post\Body\Short\View\ViewInterface;
    /** @var ViewInterface $this */

    echo $this->getResourceRenderer()->toString();
?>

<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="text">
    <?php echo $this->getMarkupTextProcessor()->prepareText($this->getPost()->getText(), $this->getLength()); ?>
    (<a href="<?php echo $this->blogGetRouteTree()->getPostTree()->buildDetailWithId($this->getPost()->getID()); ?>" class="more-link">
        <?php echo $this->translate('More...'); ?>
    </a>)
</div>
