<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Home\Component\Layout\View\ViewInterface;
    /** @var ViewInterface $this */
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getTitle(); ?></title>

    <?php
        echo $this->getResourceRenderer()->toString();
    ?>
</head>

<body>
    <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="wrapper">
        <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="margin" class="cell">
            &nbsp;
        </div>
        <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="center" class="cell">
            <a data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="title" href="/">
                <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="title" class="great">
                    PHP library <span class="great bold">GI</span>
                </div>
            </a>
            <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="navigation">
                <?php echo $this->getNaviMenu()->toString(); ?>
            </div>
            <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="content">

            </div>
        </div>
        <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="margin" class="cell">
            &nbsp;
        </div>
        <div class="clear"></div>
    </div>
</body>

</html>