<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Blog\Component\Post\Body\Full\View\ViewInterface;
    /** @var ViewInterface $this */

    echo $this->getResourceRenderer()->toString();
?>

<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="text">
    <?php $text = $this->getPost()->getText(); ?>
    <?php echo $this->getMarkupTextProcessor()->setText($text)->escapeAndReplaceEOLWithBr()->getText(); ?>
</div>
