<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Blog\Component\Comment\Usecase\Removing\View\ViewInterface;
    /** @var ViewInterface $this */

    echo $this->getResourceRenderer()->toString();
?>

<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="post">
    <?php echo $this->getPostDetailComponent()->toString(); ?>
</div>
<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="comment-detail">
    <?php echo $this->getCommentDetailComponent()->toString(); ?>
</div>
<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="delete">
    <?php echo $this->getWidget()->toString(); ?>
</div>