<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Blog\Component\Comment\Body\View\ViewInterface;
    /** @var ViewInterface $this */

    echo $this->getResourceRenderer()->toString();
?>

<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="text">
    <?php $text = $this->getComment()->getText(); ?>
    <?php echo $this->getMarkupTextProcessor()->setText($text)->escapeAndReplaceEOLWithBr()->getText(); ?>
</div>
