<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use Blog\Component\Post\Detail\Footerless\View\ViewInterface;
    /** @var ViewInterface $this */

    echo $this->getResourceRenderer()->toString();
?>

<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="header">
    <?php echo $this->getHeader()->toString(); ?>
</div>
<div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="body">
    <?php echo $this->getBody()->toString(); ?>
</div>